DaemonSet, Add Priority class
kubevirt/macvtap-cni pull request #42
Opened 2021-06-16 10:56 UTC by oshoval

Add `system-node-critical` to `macvtap-cni` DaemonSet.
Since `macvtap-cni` pod should run on each node,
assign `system-node-critical` pc to it.
This will make the control plane less sensitive to preemption
than user workloads.

Signed-off-by: Or Shoval <oshoval@redhat.com>

2021-06-16 13:21 UTC, oshoval commented
@maiqueb can you review please?

2021-06-16 14:00 UTC, maiqueb requested changes
Thanks, this might be a really good catch.

I think it makes sense, but I find it strange I found no mention whatsoever of this when I checked the multus / kubevirt / ... projects.

For instance, I find it strange to find the macvtap-(dp+cni) pod more important than virt-handler. 

Do you mind pointing out some examples of where this is used ?

2021-06-17 06:43 UTC, oshoval commented
> Do you mind pointing out some examples of where this is used ?

Some PRs that are freshly merged
https://github.com/kubevirt/bridge-marker/pull/23
https://github.com/nmstate/kubernetes-nmstate/pull/777
https://github.com/kubevirt/cluster-network-addons-operator/pull/895

As part of the effort on https://bugzilla.redhat.com/show_bug.cgi?id=1953482
We created a design that assign to all network pods either system-cluster-critical or system-node-critical,
the way we choose which one of those is if it should run on all nodes or not.
In case it should run on all nodes we put it on higher priority (system-node-critical as this PR),
because if it will be preempted it won't help to just schedule it on another node.

Its true that now network component will have higher priority than kubevirt, but its per design.

Will update the PR with more info as the 2nd comment say as well.

2021-06-17 09:39 UTC, oshoval commented on templates/macvtap.yaml.in
> +      priorityClassName: system-node-critical
Tried, ptal

2021-06-17 09:43 UTC, phoracek commented
> Its true that now network component will have higher priority than kubevirt, but its per design,
since those are mandatory pods for healthy system
(Kubevirt uses custom kubevirt-cluster-critical)

Note that KubeVirt should switch to native classes too https://bugzilla.redhat.com/show_bug.cgi?id=1953479.

The relative priority between this CNI and KubeVirt is not really that important. To  give you a backstory for this - on environments where a single node is used for both user workload and control-plane, control-plane pods should never starve out on account of user workload. If we preempt all user workload and there is still not enough space for both CNI and KubeVirt, the cluster is just flawed and can never function.

2021-06-17 09:58 UTC, maiqueb approved these changes
Thanks.

2021-06-17 10:03 UTC, phoracek requested changes
You have to rebuild manifests: https://github.com/kubevirt/macvtap-cni/blob/main/manifests/macvtap.yaml

2021-06-17 10:20 UTC, oshoval commented
> You have to rebuild manifests: https://github.com/kubevirt/macvtap-cni/blob/main/manifests/macvtap.yaml

Nice done thanks

we should add check for that i think ?
like we have on kubevirt

2021-06-17 10:22 UTC, maiqueb commented
> > You have to rebuild manifests: https://github.com/kubevirt/macvtap-cni/blob/main/manifests/macvtap.yaml
> 
> Nice done thanks
> 
> we should add check for that i think ?
> like we have on kubevirt

I guess we should, at least when the templates are updated. 

You're welcome to implement that, if you want.

2021-06-17 10:23 UTC, phoracek commented
> You're welcome to implement that, if you want.

It already is :P I'm just asking Or to call `make manifests` and push again.

2021-06-17 10:24 UTC, phoracek approved these changes
/lgtm

2021-06-17 10:26 UTC, merged