cni: stop setting ARP proxy
kubevirt/macvtap-cni pull request #44
Opened 2021-06-23 15:38 UTC by maiqueb

**What this PR does / why we need it**:
We've copied this part of the code from the macvlan cni
implementation, and apparently that code was a mistake - [0].

They wanted to enable arp notify, not arp proxy.

[0] - https://github.com/containernetworking/plugins/commit/e31cd2ce1a251bed484c579cf1a1d35c30c7a26b

**Special notes for your reviewer**:
We should really check if we then need to enable the ARP notification thingy before merging this.

2021-06-23 15:38 UTC, maiqueb commented
/hold

Let's figure out if we need to activate the ARP notifier.

2021-06-23 15:39 UTC, maiqueb commented
/approve cancel
/hold cancel

2021-08-23 09:31 UTC, maiqueb commented
/hold cancel

Ran kubevirt's e2e tests against this image; works as expected.

2021-08-23 09:41 UTC, phoracek requested changes
Sounds good, just a minor comment

2021-08-23 09:41 UTC, phoracek commented on pkg/util/netlink.go
> -	ipv4SysctlValueName := fmt.Sprintf(IPv4InterfaceArpProxySysctlTemplate, ifaceNameAllowingDots)
I think we can remove the constant now?

2021-08-23 09:47 UTC, maiqueb commented on pkg/util/netlink.go
> -	ipv4SysctlValueName := fmt.Sprintf(IPv4InterfaceArpProxySysctlTemplate, ifaceNameAllowingDots)
Right, it is no longer used.

2021-08-23 09:48 UTC, phoracek approved these changes
/lgtm

2021-08-23 09:52 UTC, merged